### ISSUE TITLE
Allow for higher zoom level map tiles

### ISSUE THREAD

**Issue by daniel-j-h** [ubipo/osmfocus#5]
It seems like the map tiles have a max zoom level, but the map itself does not.

Is there a reason the map tiles max out at a specific zoom level? Should the map then also have this zoom level as a max set? Otherwise the map tiles show up all blurry in the map view (see below).

![Screenshot_20210313-025436](https://user-images.githubusercontent.com/527241/111035134-46b13700-8419-11eb-8559-42dee24421c5.jpg)

![Screenshot_20210313-025538(1)](https://user-images.githubusercontent.com/527241/111035133-45800a00-8419-11eb-9903-749849939429.jpg)

**Comment by ubipo** [comment]
The max zoom level OSM Carto and CartoDB base maps offer is 19.

But I agree it looks kinda ugly. Because I personally do like zooming beyond 19 (even though it looks blurry) I think there are two solutions:
- Set the map's max zoom level to some golden mean between the tile layer's max zoom and the everything-gets-blurry zoom level
- Add a user-personal setting

**Comment by ubipo** [comment]
Alrighty, added a setting to turn on or off zooming beyond the basemap's maximum zoom level in 030db2e. I'll post here once that version is live.

![Screenshot_20210411-154851__01](https://user-images.githubusercontent.com/11903688/114306882-a3b61080-9add-11eb-9ffe-5443fed2228c.jpg)
