### ISSUE TITLE
F-Droid version shows up in Google Play updater and won't update

### ISSUE THREAD

**Issue by squeak9** [ubipo/osmfocus#60]
I installed this app from F-Droid and yet this recent update shows up in Google Play and I can't get rid of it, it shows the error `Can't install osmfocus reborn` when trying to update. I did the "send feedback" thing in GP, not sure if that gets to you in some way but it was worth a shot.

I feel I use a lot of F-Droid apps that are on GP but this never happens, I hoped that the update coming to F-Droid would solve the problem but it didn't. Any ideas?

~~The app itself works fine.~~
Edit: Wait, now I had issues downloading osm data and uninstalling and reinstalling the older version on F-Droid fixed it.. Maybe it is updating in a problematic way?
pps: no, tried the latest version on F-Droid and it has the same issue. Should be a different error report I guess.

**Comment by ubipo** [comment]
F-Droid releases are signed by a different key than ones from Google Play. You cannot update an app with a different signing key that the installed version, so that might explain the 'Can't install' error. In general, do not mix and match updates from Google Play and F-Droid. They are not the same app. The Google Play version for example included (don't remember if it still does) Google's billing library, and the F-Droid version includes external links.

I notice the latest version on F-Droid is 1.6.0, while on Google Play it's 1.6.1, which would explain why Google Play gives you the option to update. I'd give F-Droid a day or two more to catch up and build the package. Hopefully that will make it so Google Play doesn't prompt you to update anymore.

Closing for now as can't fix.
